spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/playdata
    username: root
    password: playdata

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none #create #none #update #validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        
  mail :
     host : smtp.gmail.com
     port : 587
     username : 'your email'
     password : 'your password'
     properties :
         mail :
            smtp :
                auth : true
                starttls :
                     enable : true 

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    com: #failed to connect to service endpoint
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    s3:
      bucket: wowplaydata
    region:
      static: ap-northeast-2
    credentials:
      instance-profile: true
    stack:
      auto: false